# Generated by Django 2.0.7 on 2018-09-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='desc',
        ),
    ]
