# Generated by Django 2.0.7 on 2018-09-17 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(default='G3BIpNS1', max_length=8)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 9, 17, 18, 39, 6, 502129, tzinfo=utc))),
                ('activated_at', models.DateTimeField()),
            ],
        ),
    ]
