# Generated by Django 2.1.1 on 2018-09-22 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20180922_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 17, 8, 51, 382564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='8ptud8hH', max_length=8),
        ),
    ]
