# Generated by Django 2.1.1 on 2018-10-04 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20180927_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 8, 5, 58, 62445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='hUcK0Kai', max_length=8),
        ),
    ]
