# Generated by Django 2.0.7 on 2018-09-17 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0004_auto_20180916_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 18, 36, 23, 562555, tzinfo=utc)),
        ),
    ]
