# Generated by Django 2.0.7 on 2018-09-18 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0007_auto_20180917_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 7, 35, 31, 581968, tzinfo=utc)),
        ),
    ]
