# Generated by Django 2.1.1 on 2018-09-27 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0010_auto_20180922_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 17, 36, 25, 760888, tzinfo=utc)),
        ),
    ]
